mod 'nexus',
  :git => 'git@github.com:cescoffier/puppet-nexus.git',
  :ref => 'master'

mod 'wildfly',
  :git => 'git@github.com:jairojunior/biemond-wildfly.git',
  :ref => 'master'

mod 'modcluster',
  :git => 'git@github.com:jairojunior/puppet-modcluster.git',
  :ref => 'master'

mod 'stdlib',
  :git => 'git@github.com:puppetlabs/puppetlabs-stdlib.git',
  :ref => 'master'

mod 'wget',
  :git => 'git@github.com:maestrodev/puppet-wget.git',
  :ref => 'master'

mod 'apache',
  :git => 'git@github.com:puppetlabs/puppetlabs-apache.git',
  :ref => 'master'

mod 'firewall',
  :git => 'git@github.com:puppetlabs/puppetlabs-firewall',
  :ref => 'master'